# 1. Image de base
FROM ubuntu:latest

# 2. Mise à jour des dépôts
RUN apt-get update

# 3. Mise à niveau des paquets installés
RUN apt-get upgrade -y

# 4. Commande exécutée au démarrage du conteneur
CMD ["echo", "Hello, World!"]
